### ISSUE TITLE
can't export a human 

### ISSUE THREAD

**Issue by loompa** [OliverJPost/HumGen3D#113]
process -> export human does not work (with different settings)
so far only texture baking works

I attach example screen recording, though steps could be a little different and I still get this error
Also attaching screenshot with an error from python

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4
 - Blender Version Version 4.0.2 (4.0.2 2023-12-05)
 - Human Generator VersionHumGen3D_V4_0_18
<img width="772" alt="Screenshot 2024-05-19 at 2 40 54 PM" src="https://github.com/OliverJPost/HumGen3D/assets/19569556/6658c232-a917-49fc-bcb1-86a2b3cb0f7a">

https://github.com/OliverJPost/HumGen3D/assets/19569556/95c5f05b-591f-4170-bac9-0a7cff074c24

**Comment by miket79** [comment]
Yes, I have the same problem, and when you manage to export a model, the hairs go out of orbit, definitely this issue is the Achilles heel of this ad-on not only for MAC but also for windows, they should work on a better version of exporting, which gives more freedom to the creator because without a doubt this is an easy solution but something tells me that they want to keep the buyer within their own resolution environment!
