### ISSUE TITLE
Sitting pose cause feet to go through ground plane

### ISSUE THREAD

**Issue by OliverJPost** [OliverJPost/HumGen3D#12]
**Describe the bug**
When using a seated pose on a human with non-standard height, the feet clip trough the ground plane

**To Reproduce**
1. Create new human
2. Change height to a non-standard value like 160 cm
3. Finish creation phase4. 
4. Select seated pose

**Possible causes**
Origin imprecision of height changing system

**Comment by mtmorrione** [comment]
Yes, this accurately describes the bug.
I think a work around, if known, should be added by poster and possibly a comment by HG. This is really important since it may take a while to fix the bug and depending on the bug it may take 
In this case:
Work Around: Move HG character rig until feet touch desired surface and adjust origin to feet.

**Comment by OliverJPost** [comment]
Should be fixed in V4
