### ISSUE TITLE
Render lighting is really off

### ISSUE THREAD

**Issue by luxfps** [OliverJPost/HumGen3D#126]
Hey so I ran into this issue while trying to render a scene with HumanGen model. Basically, the lighting seems really off, it's like the textures have some kind of emission on their own, which should not be the case. I checked everything I know off, I tried every solution from the internet I could find, but there is no reason for it. No extra emission node, all other emissions set to 0. Is this a bug, or am I doing something wrong?
This is how it looks like:

![normalscene](https://github.com/user-attachments/assets/311547f2-0460-47ca-b659-bc61b4fe22a5)
![weird shadows](https://github.com/user-attachments/assets/20b4fb6a-8b12-479a-8fb0-4e9be23dbde0)
![glow textures wtf](https://github.com/user-attachments/assets/142f5dc8-2212-4091-ac59-0286d1d4bfb1)

Thank you for any fixes or advice!

**Comment by OliverJPost** [comment]
To me, it very much looks like there is a point/sun light or other light source in the scene that perhaps is set to not visible in viewport, but visible for the final render. Emission on the textures would result in even illumination from the texture, not some dark and some light areas.
![CleanShot 2024-12-16 at 16 09 59@2x](https://github.com/user-attachments/assets/e172b292-7c9e-409b-accb-9b51f5e6cea4)
It looks like there is the "custom" object that doesn't show in viewport, but does render. Does that have emission properties? Otherwise there does seem to be a light source in the scene

**Comment by OliverJPost** [comment]
Glad to hear!
