### ISSUE TITLE
Using version 4. I've noticed when using male characters that when I go into Blender's Edit Mode, the mesh changes to a default female character regardless of which male starting character I'm using? When using female characters and entering Blender's Edit Mode, the mesh stays  the same as it is in Blender's Object mode and seems to be working correctly. This needs resolving please as no minor edits / refinements to the mesh can be made when using the male character's mesh as the mesh isn't the one that is being worked on at the time etc. This is obviously a bug as the female character works fine etc?

### ISSUE THREAD

**Issue by Googey1** [OliverJPost/HumGen3D#51]
**Describe the bug**
A clear and concise description of what the bug is. If you get an error message, please copy-paste it or add a screenshot of it.

**To Reproduce**
3. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, MacOS Ventura]
 - Blender Version [e.g. 3.0.2]
 - Human Generator Version [e.g. 3.0.0]

**Comment by OliverJPost** [comment]
Expected behaviour. This is due to the male shape being a shape key on top of the female base mesh.
Use "apply shape keys in edit mode" to edit either a new shape key or existing ones with the male shape active.
<img width="195" alt="Screenshot 2023-02-21 at 11 11 30" src="https://user-images.githubusercontent.com/65900202/220315444-9c89788b-6732-4ff2-9fa2-862c123776f6.png">
